<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE tienda [
    <!ELEMENT tienda (producto*)>

    <!-- 
        elemento -> Sólo puede haber 1 elemento
        elemento+ -> Uno o más elementos
        elemento* -> Ninguno, uno o más elmentos
        elemento? -> Ninguno o uno (elemento opcional)
    -->

    <!ELEMENT producto (nombre, descripcion?, stock)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT descripcion (#PCDATA)>
    <!ELEMENT stock (#PCDATA)>
]>

<tienda>
    <producto>
        <nombre>Alhambra II</nombre>
        <descripcion>Placa con FPGA ice40HX8K</descripcion>
        <stock>3</stock>
    </producto>

    <producto>
        <nombre>Icestick</nombre>
        <stock>10</stock>
    </producto>
</tienda>